version: "3"
services:
  qtumcore:
    build: .
    volumes:
      - qtumcoreblocks:/home/node/app/qtumNode/data/blocks
      - qtumcoretestnet:/home/node/app/qtumNode/data/testnet3
    ports:
      - "3013:3001"
      - "28312:28332"
      - "3711:13888"

volumes:
  qtumcoreblocks:
  qtumcoretestnet:
