version: "3"
services:
  qtumcore:
    build: .
    volumes:
      - qtumcore:/home/node/app/qtumNode/data
    ports:
      - "3003:3001"
      - "28332:28332"
      - "3701:8332"

volumes:
  qtumcore:
